name: Upload Executable to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Decode and set up Google Drive credentials
      run: |
        $base64String = "${{ secrets.GDRIVE_CREDENTIALS_BASE64 }}"
        [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($base64String)) | Out-File -FilePath credentials.json -Encoding utf8
        Write-Host "==== BEGIN credentials.json ===="
        Get-Content credentials.json
        Write-Host "==== END credentials.json ===="

    - name: Upload to Google Drive
      run: python upload_to_gdrive.py
