name: Upload Executable to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Decode and set up Google Drive credentials
      run: |
        echo ${{ secrets.GDRIVE_CREDENTIALS_BASE64 }} | base64 --decode > credentials.json
        cat credentials.json

    - name: Upload to Google Drive
      run: python upload_to_gdrive.py
