name: Upload Executable

on:
  workflow_run:
    workflows: ["Build Executable"]
    types:
      - completed

jobs:
  upload:
    runs-on: windows-latest  # Ensure this is set to Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Upload EXE to Google Drive
        run: |
          gdrive files upload --parent 1xOg_0Q2gEBWdn-VZGDK9DSpQxeAyORTB output/my_executable.exe
